### ISSUE TITLE
setup.xml not declared error

### ISSUE THREAD

**Issue by ianc99** [kakopappa/arduino-esp8266-alexa-multiple-wemo-switch#28]
Hi,
I'm getting "Switch.cpp:214: error: 'setup_xml' was not declared in this scope" error when trying to compile.  The fix is obvious (I think), but I just want to check if I've pulled down the right version which has the ability to respond to Alexa status requests.  Or am I doing something stupid :-)

Thanks

**Comment by Antoinebr** [comment]
I also have the same issue  

```
sketch/Switch.cpp: In member function 'void Switch::sendRelayState()':
Switch.cpp:214: error: 'setup_xml' was not declared in this scope
   Serial.println(setup_xml);
                  ^
exit status 1
'setup_xml' was not declared in this scope

```

**Comment by ianc99** [comment]
I just replaced it with
` Serial.println(body);`
and it worked

**Comment by kakopappa** [comment]
sorry about that guys. I have updated the code now.
