### ISSUE TITLE
Not an issue , Did i's possible over ifttt ou other thing to use it via Google Home : I'm frensh

### ISSUE THREAD

**Issue by TomAvecLeVdsl** [kakopappa/arduino-esp8266-alexa-multiple-wemo-switch#47]
Hi everyone (My english is bad :) it's normal i'm frensh)
So i try to do it working with Wemo app but it's not work 
So i want to now if it's possible via IFTTT or other things

Thanks for replies

**Comment by victorantonio21** [comment]
The Wemo App will not find this fake devices, this code is designed for alexa only, You can make it your own another code based on this one, or find another one on the web that works with another devices, like google home (You should use Sinric) or Siri (Homekit / homebridge). do some research on google with your specified desire. 
And yes, there's a code for IFTTT to trigger on/off switches by alexa and other IFTTT compatible devices, but i haven't tested it yet
