### ISSUE TITLE
Add a push button to manually turn on/off the lights

### ISSUE THREAD

**Issue by ChompsR** [kakopappa/arduino-esp8266-alexa-multiple-wemo-switch#74]
Good evening

I've been working on this project for the last week, so it came this idea to add a push button to manually turn on and off the lights. After studying where this instructions had to be placed, I finally found that is on Switch.cpp (continue reading). 

There's a void called Switch::handleUpnpControl() which I presume this is the one that controls when you ask Alexa to turn on/off the device, this is where I add some code lines to include a push button. 

**RESULTS:**
- I can get Alexa to turn on/off the device.
- The code detects the push button BUT **it only makes changes when the button is pressed and I had to ask Alexa to turn on/off the lights**. I thought this can be because there's some statement that I can not found yet that takes the instruction direct to this void.

Any ideas of how we could add this button to had a fully functional smart device? 

I also added some new lines to the original Wemos page to make the device smarter, I will upload the pull request once the push button is coded.

Things I added:
 - Automatic reset when connection lost or not found.
- Detection for and OLED display to show a little logo, SSID and IP address.

For this changes stay tuned.

This is what I modified on Switch.cpp:

<pre>
<font color="#00979c">void</font> <font color="#000000">Switch</font><font color="#434f54">:</font><font color="#434f54">:</font><font color="#000000">handleEventservice</font><font color="#000000">(</font><font color="#000000">)</font><font color="#000000">{</font>
 &nbsp;<b><font color="#d35400">Serial</font></b><font color="#434f54">.</font><font color="#d35400">println</font><font color="#000000">(</font><font color="#005c5f">&#34; ########## Responding to eventservice.xml ... ########\n&#34;</font><font color="#000000">)</font><font color="#000000">;</font>
 &nbsp;
 &nbsp;<font color="#00979c">String</font> <font color="#000000">eventservice_xml</font> <font color="#434f54">=</font> <font color="#005c5f">&#34;&lt;scpd xmlns=\&#34;urn:Belkin:service-1-0\&#34;&gt;&#34;</font>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font color="#005c5f">&#34;&lt;actionList&gt;&#34;</font>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font color="#005c5f">&#34;&lt;action&gt;&#34;</font>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font color="#005c5f">&#34;&lt;name&gt;SetBinaryState&lt;&#47;name&gt;&#34;</font>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font color="#005c5f">&#34;&lt;argumentList&gt;&#34;</font>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font color="#005c5f">&#34;&lt;argument&gt;&#34;</font>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font color="#005c5f">&#34;&lt;retval&#47;&gt;&#34;</font>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font color="#005c5f">&#34;&lt;name&gt;BinaryState&lt;&#47;name&gt;&#34;</font>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font color="#005c5f">&#34;&lt;relatedStateVariable&gt;BinaryState&lt;&#47;relatedStateVariable&gt;&#34;</font>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font color="#005c5f">&#34;&lt;direction&gt;in&lt;&#47;direction&gt;&#34;</font>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font color="#005c5f">&#34;&lt;&#47;argument&gt;&#34;</font>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font color="#005c5f">&#34;&lt;&#47;argumentList&gt;&#34;</font>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font color="#005c5f">&#34;&lt;&#47;action&gt;&#34;</font>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font color="#005c5f">&#34;&lt;action&gt;&#34;</font>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font color="#005c5f">&#34;&lt;name&gt;GetBinaryState&lt;&#47;name&gt;&#34;</font>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font color="#005c5f">&#34;&lt;argumentList&gt;&#34;</font>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font color="#005c5f">&#34;&lt;argument&gt;&#34;</font>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font color="#005c5f">&#34;&lt;retval&#47;&gt;&#34;</font>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font color="#005c5f">&#34;&lt;name&gt;BinaryState&lt;&#47;name&gt;&#34;</font>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font color="#005c5f">&#34;&lt;relatedStateVariable&gt;BinaryState&lt;&#47;relatedStateVariable&gt;&#34;</font>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font color="#005c5f">&#34;&lt;direction&gt;out&lt;&#47;direction&gt;&#34;</font>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font color="#005c5f">&#34;&lt;&#47;argument&gt;&#34;</font>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font color="#005c5f">&#34;&lt;&#47;argumentList&gt;&#34;</font>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font color="#005c5f">&#34;&lt;&#47;action&gt;&#34;</font>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font color="#005c5f">&#34;&lt;&#47;actionList&gt;&#34;</font>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font color="#005c5f">&#34;&lt;serviceStateTable&gt;&#34;</font>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font color="#005c5f">&#34;&lt;stateVariable sendEvents=\&#34;yes\&#34;&gt;&#34;</font>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font color="#005c5f">&#34;&lt;name&gt;BinaryState&lt;&#47;name&gt;&#34;</font>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font color="#005c5f">&#34;&lt;dataType&gt;Boolean&lt;&#47;dataType&gt;&#34;</font>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font color="#005c5f">&#34;&lt;defaultValue&gt;0&lt;&#47;defaultValue&gt;&#34;</font>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font color="#005c5f">&#34;&lt;&#47;stateVariable&gt;&#34;</font>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font color="#005c5f">&#34;&lt;stateVariable sendEvents=\&#34;yes\&#34;&gt;&#34;</font>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font color="#005c5f">&#34;&lt;name&gt;level&lt;&#47;name&gt;&#34;</font>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font color="#005c5f">&#34;&lt;dataType&gt;string&lt;&#47;dataType&gt;&#34;</font>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font color="#005c5f">&#34;&lt;defaultValue&gt;0&lt;&#47;defaultValue&gt;&#34;</font>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font color="#005c5f">&#34;&lt;&#47;stateVariable&gt;&#34;</font>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font color="#005c5f">&#34;&lt;&#47;serviceStateTable&gt;&#34;</font>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font color="#005c5f">&#34;&lt;&#47;scpd&gt;\r\n&#34;</font>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font color="#005c5f">&#34;\r\n&#34;</font><font color="#000000">;</font>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
 &nbsp;&nbsp;&nbsp;<font color="#000000">server</font><font color="#434f54">-</font><font color="#434f54">&gt;</font><font color="#d35400">send</font><font color="#000000">(</font><font color="#000000">200</font><font color="#434f54">,</font> <font color="#005c5f">&#34;text&#47;plain&#34;</font><font color="#434f54">,</font> <font color="#000000">eventservice_xml</font><font color="#434f54">.</font><font color="#000000">c_str</font><font color="#000000">(</font><font color="#000000">)</font><font color="#000000">)</font><font color="#000000">;</font>
<font color="#000000">}</font>
 
<font color="#00979c">void</font> <font color="#000000">Switch</font><font color="#434f54">:</font><font color="#434f54">:</font><font color="#000000">handleUpnpControl</font><font color="#000000">(</font><font color="#000000">)</font><font color="#000000">{</font>
 &nbsp;<b><font color="#d35400">Serial</font></b><font color="#434f54">.</font><font color="#d35400">println</font><font color="#000000">(</font><font color="#005c5f">&#34;########## Responding to &nbsp;&#47;upnp&#47;control&#47;basicevent1 ... ##########&#34;</font><font color="#000000">)</font><font color="#000000">;</font> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
 &nbsp;
 &nbsp;<font color="#434f54">&#47;&#47;for (int x=0; x &lt;= HTTP.args(); x++) {</font>
 &nbsp;<font color="#434f54">&#47;&#47; &nbsp;Serial.println(HTTP.arg(x));</font>
 &nbsp;<font color="#434f54">&#47;&#47;}</font>

<font color="#d35400">pinMode</font><font color="#000000">(</font><font color="#000000">Boton</font><font color="#434f54">,</font><font color="#00979c">INPUT_PULLUP</font><font color="#000000">)</font><font color="#000000">;</font> <font color="#434f54">&#47;&#47; PUSH BUTTON</font>
<font color="#000000">Estado</font> <font color="#434f54">=</font> <font color="#d35400">digitalRead</font><font color="#000000">(</font><font color="#000000">Boton</font><font color="#000000">)</font><font color="#000000">;</font> <font color="#434f54">&#47;&#47; STATE</font>

 &nbsp;<font color="#00979c">String</font> <font color="#000000">request</font> <font color="#434f54">=</font> <font color="#000000">server</font><font color="#434f54">-</font><font color="#434f54">&gt;</font><font color="#d35400">arg</font><font color="#000000">(</font><font color="#000000">0</font><font color="#000000">)</font><font color="#000000">;</font> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
 &nbsp;<b><font color="#d35400">Serial</font></b><font color="#434f54">.</font><font color="#d35400">print</font><font color="#000000">(</font><font color="#005c5f">&#34;request:&#34;</font><font color="#000000">)</font><font color="#000000">;</font>
 &nbsp;<b><font color="#d35400">Serial</font></b><font color="#434f54">.</font><font color="#d35400">println</font><font color="#000000">(</font><font color="#000000">request</font><font color="#000000">)</font><font color="#000000">;</font>
 &nbsp;

 &nbsp;<font color="#5e6d03">if</font><font color="#000000">(</font><font color="#000000">request</font><font color="#434f54">.</font><font color="#d35400">indexOf</font><font color="#000000">(</font><font color="#005c5f">&#34;SetBinaryState&#34;</font><font color="#000000">)</font> <font color="#434f54">&gt;=</font> <font color="#000000">0</font><font color="#000000">)</font> <font color="#000000">{</font>
 &nbsp;&nbsp;&nbsp;<font color="#5e6d03">if</font><font color="#000000">(</font><font color="#000000">request</font><font color="#434f54">.</font><font color="#d35400">indexOf</font><font color="#000000">(</font><font color="#005c5f">&#34;&lt;BinaryState&gt;1&lt;&#47;BinaryState&gt;&#34;</font><font color="#000000">)</font> <font color="#434f54">&gt;=</font> <font color="#000000">0</font><font color="#000000">)</font> <font color="#000000">{</font>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<b><font color="#d35400">Serial</font></b><font color="#434f54">.</font><font color="#d35400">println</font><font color="#000000">(</font><font color="#005c5f">&#34;Got Turn on request&#34;</font><font color="#000000">)</font><font color="#000000">;</font>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font color="#000000">switchStatus</font> <font color="#434f54">=</font> <font color="#000000">onCallback</font><font color="#000000">(</font><font color="#000000">)</font><font color="#000000">;</font>

 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font color="#000000">sendRelayState</font><font color="#000000">(</font><font color="#000000">)</font><font color="#000000">;</font>
<font color="#434f54">&#47;&#47; Push Button for turning off the lights</font>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font color="#000000">Estado</font> <font color="#434f54">=</font> <font color="#d35400">digitalRead</font><font color="#000000">(</font><font color="#000000">Boton</font><font color="#000000">)</font><font color="#000000">;</font>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font color="#5e6d03">if</font><font color="#000000">(</font><font color="#000000">Estado</font> <font color="#434f54">!=</font> <font color="#00979c">HIGH</font><font color="#000000">)</font><font color="#000000">{</font>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font color="#000000">request</font><font color="#434f54">.</font><font color="#d35400">indexOf</font><font color="#000000">(</font><font color="#005c5f">&#34;&lt;BinaryState&gt;0&lt;&#47;BinaryState&gt;&#34;</font><font color="#000000">)</font> <font color="#434f54">&gt;=</font> <font color="#000000">0</font><font color="#000000">;</font>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<b><font color="#d35400">Serial</font></b><font color="#434f54">.</font><font color="#d35400">println</font><font color="#000000">(</font><font color="#005c5f">&#34;Got Turn off request&#34;</font><font color="#000000">)</font><font color="#000000">;</font>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font color="#000000">switchStatus</font> <font color="#434f54">=</font> <font color="#000000">offCallback</font><font color="#000000">(</font><font color="#000000">)</font><font color="#000000">;</font>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font color="#000000">sendRelayState</font><font color="#000000">(</font><font color="#000000">)</font><font color="#000000">;</font>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font color="#000000">}</font>
<font color="#434f54">&#47;&#47; MOD END</font>
 &nbsp;&nbsp;&nbsp;<font color="#000000">}</font>

 &nbsp;&nbsp;&nbsp;<font color="#5e6d03">if</font><font color="#000000">(</font><font color="#000000">request</font><font color="#434f54">.</font><font color="#d35400">indexOf</font><font color="#000000">(</font><font color="#005c5f">&#34;&lt;BinaryState&gt;0&lt;&#47;BinaryState&gt;&#34;</font><font color="#000000">)</font> <font color="#434f54">&gt;=</font> <font color="#000000">0</font><font color="#000000">)</font> <font color="#000000">{</font>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<b><font color="#d35400">Serial</font></b><font color="#434f54">.</font><font color="#d35400">println</font><font color="#000000">(</font><font color="#005c5f">&#34;Got Turn off request&#34;</font><font color="#000000">)</font><font color="#000000">;</font>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font color="#000000">switchStatus</font> <font color="#434f54">=</font> <font color="#000000">offCallback</font><font color="#000000">(</font><font color="#000000">)</font><font color="#000000">;</font>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font color="#000000">sendRelayState</font><font color="#000000">(</font><font color="#000000">)</font><font color="#000000">;</font>

<font color="#434f54">&#47;&#47; Push Button for turning on the lights</font>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font color="#000000">Estado</font> <font color="#434f54">=</font> <font color="#d35400">digitalRead</font><font color="#000000">(</font><font color="#000000">Boton</font><font color="#000000">)</font><font color="#000000">;</font>

 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font color="#5e6d03">if</font><font color="#000000">(</font><font color="#000000">Estado</font> <font color="#434f54">!=</font> <font color="#00979c">HIGH</font><font color="#000000">)</font><font color="#000000">{</font>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font color="#000000">request</font><font color="#434f54">.</font><font color="#d35400">indexOf</font><font color="#000000">(</font><font color="#005c5f">&#34;&lt;BinaryState&gt;1&lt;&#47;BinaryState&gt;&#34;</font><font color="#000000">)</font> <font color="#434f54">&gt;=</font> <font color="#000000">0</font><font color="#000000">;</font>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<b><font color="#d35400">Serial</font></b><font color="#434f54">.</font><font color="#d35400">println</font><font color="#000000">(</font><font color="#005c5f">&#34;Got Turn on request&#34;</font><font color="#000000">)</font><font color="#000000">;</font>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font color="#000000">switchStatus</font> <font color="#434f54">=</font> <font color="#000000">onCallback</font><font color="#000000">(</font><font color="#000000">)</font><font color="#000000">;</font>

 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font color="#000000">sendRelayState</font><font color="#000000">(</font><font color="#000000">)</font><font color="#000000">;</font>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font color="#000000">}</font>
<font color="#434f54">&#47;&#47; MOD END </font>
 &nbsp;&nbsp;&nbsp;<font color="#000000">}</font>
 
 &nbsp;<font color="#000000">}</font>

 &nbsp;<font color="#5e6d03">if</font><font color="#000000">(</font><font color="#000000">request</font><font color="#434f54">.</font><font color="#d35400">indexOf</font><font color="#000000">(</font><font color="#005c5f">&#34;GetBinaryState&#34;</font><font color="#000000">)</font> <font color="#434f54">&gt;=</font> <font color="#000000">0</font><font color="#000000">)</font> <font color="#000000">{</font>
 &nbsp;&nbsp;&nbsp;<b><font color="#d35400">Serial</font></b><font color="#434f54">.</font><font color="#d35400">println</font><font color="#000000">(</font><font color="#005c5f">&#34;Got binary state request&#34;</font><font color="#000000">)</font><font color="#000000">;</font>
 &nbsp;&nbsp;&nbsp;<font color="#000000">sendRelayState</font><font color="#000000">(</font><font color="#000000">)</font><font color="#000000">;</font>
 &nbsp;<font color="#000000">}</font>
 &nbsp;
 &nbsp;<font color="#000000">server</font><font color="#434f54">-</font><font color="#434f54">&gt;</font><font color="#d35400">send</font><font color="#000000">(</font><font color="#000000">200</font><font color="#434f54">,</font> <font color="#005c5f">&#34;text&#47;plain&#34;</font><font color="#434f54">,</font> <font color="#005c5f">&#34;&#34;</font><font color="#000000">)</font><font color="#000000">;</font>
 &nbsp;
<font color="#000000">}</font>

</pre>

Thank you very much and keep safe.

- ChompsR

**Comment by kakopappa** [comment]
Thanks for sharing. FYI Emulator technique time to time cause problems. I
have switched to amazon skill based solution now using https://sinric.pro

**Comment by ChompsR** [comment]
Kakopappa, thank you very much! Sinric Pro skill is amazing, and the codes/libraries/examples, just wow, I'm really impressed, if you don't mind I will make some changes to the Switch example just to add the lines that I've already coded on wemo's example. 

I'll be in touch!
