### ISSUE TITLE
Update status to Alexa

### ISSUE THREAD

**Issue by twlawrenceko** [kakopappa/arduino-esp8266-alexa-multiple-wemo-switch#77]
Hello,

I have also implemented MQTT with this source code, as if the switch is being turned off by MQTT, Alexa does not update the status of the switch automatically. Is there any part of the code that updates the status to Alexa?

Thanks

**Comment by kakopappa** [comment]
Hi, don’t think that’s possible with emulation method. If you really want
to achieve this and don’t mind using cloud provider, try Sinric pro
